import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#0e1322',
        'primary-container': '#00d4ff',
        'primary': '#a8e8ff',
        'secondary-container': '#454747',
        'secondary': '#c6c6c7',
        'tertiary': '#ffdc6e',
        'tertiary-container': '#e8bf24',
        'surface': '#0e1322',
        'surface-container': '#1a1f2f',
        'surface-variant': '#2f3445',
        'surface-bright': '#343949',
        'surface-container-low': '#161b2b',
        'surface-container-high': '#25293a',
        'surface-container-lowest': '#090e1c',
        'surface-container-highest': '#2f3445',
        'on-primary': '#003642',
        'on-primary-container': '#00586b',
        'on-secondary': '#2f3131',
        'on-secondary-container': '#b4b5b5',
        'on-tertiary': '#3c2f00',
        'on-tertiary-container': '#624e00',
        'on-surface': '#dee1f7',
        'on-surface-variant': '#bbc9cf',
        'on-background': '#dee1f7',
        'background': '#0e1322',
        'outline': '#859398',
        'outline-variant': '#3c494e',
        'inverse-surface': '#dee1f7',
        'inverse-on-surface': '#2b3040',
        'inverse-primary': '#00677e',
        'surface-tint': '#3cd7ff',
        'primary-fixed': '#b4ebff',
        'primary-fixed-dim': '#3cd7ff',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c7',
        'tertiary-fixed': '#ffe082',
        'tertiary-fixed-dim': '#ecc228',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
export default config
